### ISSUE TITLE
terrasnek.api.InvalidTFCTokenException

### ISSUE THREAD

**Issue by ramcharantej** [dahlke/terrasnek#47]
Hi,

I was trying to call our TFE workspace state version and found Terrasnek to do but while I'm trying to do the first step. It keeps failing with following error. I tried with several python3 versions between 3.7 to 3.11. All of them fail. 

```
`>>> import os
>>> from terrasnek.api import TFC
>>>
>>> TFC_TOKEN = os.getenv("I have Provided User API Token here", None)
>>> TFC_URL = os.getenv("My Paid TFE URL", None)  # ex: https://app.terraform.io
>>>
>>> api = TFC(TFC_TOKEN, url=TFC_URL)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/AL20827/Library/Python/3.9/lib/python/site-packages/terrasnek/api.py", line 151, in __init__
    raise InvalidTFCTokenException
terrasnek.api.InvalidTFCTokenException
>>> api.set_org("My Organization")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'api' is not defined
>>>`
```

Any thing to mitigate this issue? I'm sure I was not missing anything to atleast to get started with Terrasnek.

**Comment by ramcharantej** [comment]
This was export variable issue.
